# Generated by Django 3.1.1 on 2021-01-22 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField(unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure_data.mattress')),
            ],
        ),
        migrations.CreateModel(
            name='PressureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('l_x', models.IntegerField()),
                ('l_y', models.IntegerField()),
                ('p', models.FloatField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure_data.mattress')),
            ],
        ),
    ]
