# Generated by Django 3.1.1 on 2021-01-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressureentry',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure_data.reportcycle'),
        ),
    ]
