# Generated by Django 3.1.1 on 2021-01-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure_data.mattress')),
            ],
        ),
    ]
