# Generated by Django 3.1.1 on 2021-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0002_reportcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcycle',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
