# Generated by Django 3.1.1 on 2021-01-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0003_auto_20210121_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressureentry',
            old_name='mat_id',
            new_name='mat',
        ),
    ]
