# Generated by Django 3.1.1 on 2021-01-22 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0004_auto_20210121_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='serial',
            field=models.TextField(default=datetime.datetime(2021, 1, 22, 7, 55, 56, 571740, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
