# Generated by Django 3.1.1 on 2021-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_data', '0006_auto_20210122_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress',
            name='serial',
            field=models.TextField(unique=True),
        ),
    ]
