# Generated by Django 3.1.1 on 2021-04-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personalrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fcm_token',
        ),
    ]
