# Generated by Django 3.1.1 on 2021-04-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalRisk',
        ),
    ]
