# Generated by Django 3.1.1 on 2021-04-06 13:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UlcerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('back_of_head', 'Back of Head'), ('forehead', 'Forehead'), ('right_shoulder', 'Right Shoulder'), ('left_shoulder', 'Left Shoulder'), ('right_heel', 'Right Heel'), ('left_heel', 'Left Heel'), ('left_elbow', 'Left Elbow'), ('right_elbow', 'Right Elbow'), ('right_buttock', 'Right Buttock'), ('left_buttock', 'Left Buttock'), ('right_knee', 'Right Knee'), ('left_knee', 'Left Knee'), ('left_hip', 'Left Hip'), ('right_hip', 'Right Hip'), ('fingers', 'Fingers'), ('toes', 'Toes'), ('other', 'Other')], max_length=50)),
                ('stage', models.CharField(choices=[('I', 'Stage I'), ('II', 'Stage II'), ('III', 'Stage III'), ('IV', 'Stage IV'), ('DTI', 'DTI'), ('UN', 'Unstaged')], max_length=20)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('margin', models.CharField(choices=[('reg', 'Regular'), ('irreg', 'Irregular')], max_length=8)),
                ('edge', models.CharField(choices=[('sloping', 'Sloping'), ('punched_out', 'Punched out'), ('rollout', 'Rollout'), ('everted', 'Everted')], max_length=20)),
                ('edge_color', models.CharField(max_length=50)),
                ('underminings', models.BooleanField(default=False)),
                ('sinus_tracts', models.BooleanField(default=False)),
                ('floor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('healthy', 'Healthy'), ('granulation', 'Granualation Tissue'), ('slough', 'Slough'), ('necrotic', 'Necrotic'), ('eschar', 'Eschar'), ('epithelial', 'Epithelial')], max_length=50), size=None)),
                ('discharge', models.CharField(choices=[('serous', 'Serous'), ('purulent', 'Purulent'), ('serosanguineous', 'Serosanguineous'), ('other', 'Other')], max_length=50)),
                ('discharge_amount', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('h', 'Heavy')], max_length=50)),
                ('surrounding_skin', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('warm', 'Warm'), ('thickend', 'Thickend'), ('hyperpigmented', 'Hyperpigmented'), ('hypopignmented', 'Hypopignmented'), ('gangrenous', 'Gangreous')], max_length=50), size=None)),
                ('skin_sensation', models.CharField(choices=[('g', 'Good'), ('b', 'Impaired')], max_length=50)),
                ('regional_lymph_nodes_enlarged', models.BooleanField(default=False)),
                ('smell', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('progress', models.CharField(choices=[('improved', 'Improved'), ('no_change', 'NO Change'), ('stable', 'Stable'), ('declined', 'Declined')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ulcers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
