# Generated by Django 3.1.1 on 2021-04-06 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulcer_documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulcerrecord',
            name='floor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('granulation', 'Granualation Tissue'), ('slough', 'Slough'), ('necrotic', 'Necrotic'), ('eschar', 'Eschar'), ('epithelial', 'Epithelial')], max_length=50), size=6),
        ),
        migrations.AlterField(
            model_name='ulcerrecord',
            name='stage',
            field=models.CharField(choices=[('I', 'Stage I'), ('II', 'Stage II'), ('III', 'Stage III'), ('IV', 'Stage IV'), ('DTI', 'Deep Tissue Injury'), ('UN', 'Unstaged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ulcerrecord',
            name='surrounding_skin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('thickend', 'Thickend'), ('hyperpigmented', 'Hyperpigmented'), ('hypopignmented', 'Hypopignmented'), ('gangrenous', 'Gangreous')], max_length=50), size=5),
        ),
    ]
