# Generated by Django 3.1.1 on 2021-04-06 14:21

from django.db import migrations, models
import ulcer_documentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('ulcer_documentation', '0002_auto_20210406_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulcerrecord',
            name='floor',
            field=ulcer_documentation.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('granulation', 'Granualation Tissue'), ('slough', 'Slough'), ('necrotic', 'Necrotic'), ('eschar', 'Eschar'), ('epithelial', 'Epithelial')], max_length=50), size=6),
        ),
        migrations.AlterField(
            model_name='ulcerrecord',
            name='surrounding_skin',
            field=ulcer_documentation.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('thickend', 'Thickend'), ('hyperpigmented', 'Hyperpigmented'), ('hypopignmented', 'Hypopignmented'), ('gangrenous', 'Gangreous')], max_length=50), size=5),
        ),
    ]
