# Generated by Django 3.1.1 on 2021-04-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulcer_documentation', '0004_auto_20210406_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulcerrecord',
            name='discharge',
            field=models.CharField(blank=True, choices=[('serous', 'Serous'), ('purulent', 'Purulent'), ('serosanguineous', 'Serosanguineous'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ulcerrecord',
            name='discharge_amount',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('h', 'Heavy')], max_length=50, null=True),
        ),
    ]
