# Generated by Django 3.1.1 on 2021-04-07 04:06

from django.db import migrations, models
import ulcer_documentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('ulcer_documentation', '0005_auto_20210407_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulcerrecord',
            name='surrounding_skin',
            field=ulcer_documentation.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('thickend', 'Thickend'), ('hyperpigmented', 'Hyperpigmented'), ('hypopignmented', 'Hypopignmented'), ('gangrenous', 'Gangreous'), ('itching', 'Itching'), ('swelling', 'Swelling')], max_length=50), size=5),
        ),
    ]
