# Generated by Django 3.1.1 on 2021-04-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_assessment', '0003_riskscale_venus_thrombosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskscale',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scale', to=settings.AUTH_USER_MODEL),
        ),
    ]
